---
title: "Homework 6"
author: "Vincent Tam"
date: "November 25, 2018"
output: github_document
---
Problem 1 - Homicide Data
```{r, warning = FALSE, echo = FALSE}
library(tidyverse)
library(janitor)
library(dplyr)
library(purrr)
set.seed(12345)
```
```{r upload and clean data, warning = FALSE, echo = FALSE}
hom_data <- read.csv(file = "./homicide-data.csv") 
hom_data = 
  hom_data %>%
  mutate(city_state = str_c(city, ",", state)) %>%
  filter(city_state != "Dallas,TX", city_state != "Phoenix,AZ", city_state != "Kansas City,MO", city_state != "Tulsa,AL") %>% 
  filter(victim_sex != "Unknown") %>%
  mutate(victim_sex = as.factor(victim_sex)) %>%
  mutate(victim_race = recode(victim_race, 'White' = "White", 'Hispanic' = "Non_white", 'Other' = "Non_white", 'Black' = "Non_white", 'Asian' = "Non_white", 'Unknown' = "Non_white")) %>% 
  mutate(solved = as.numeric(disposition == "Closed by arrest"),
         victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White", "Non_white")) %>% 
  mutate(victim_age = as.numeric(victim_age)) 
```
```{r Baltimore homicides, warning = FALSE, echo = FALSE}
baltimore_data = 
  hom_data %>%
  filter(city_state == "Baltimore,MD")
baltimore_fit = 
  baltimore_data %>% 
  glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(OR = boot::inv.logit(estimate)) %>%
  select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)
```
```{r all cities homicides, warning = FALSE, echo = FALSE}
cities_glinmodel = 
  hom_data %>% 
  group_by(city_state) %>%
  select(city_state, solved, victim_age, victim_race, victim_sex) %>%
  nest() %>% 
  mutate(glinmodel = map(data, ~glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()))) %>%
  mutate(glinmodel_tidy = map(glinmodel, ~broom::tidy(.))) %>%
  mutate(glinmodel_ci = map(glinmodel, ~broom::confint_tidy(.))) %>%
  select(city_state, glinmodel_tidy, glinmodel_ci) %>% 
  unnest() %>% 
  mutate(OR = exp(estimate), OR.conf.low = exp(conf.low), OR.conf.high = exp(conf.high)) %>%
  select(city_state, term, log_OR = estimate, OR, p.value, OR.conf.low, OR.conf.high) %>% 
  filter(term == "victim_raceNon_white")
cities_plot =
  cities_glinmodel %>% 
  mutate(city_state = reorder(city_state, OR), OR) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_errorbar(aes(ymin = OR.conf.low, ymax = OR.conf.high)) +
  geom_point() +
  labs(
    title = "Estimate OR and CIs for All Cities",
    x = "City",
    y = "OR Estimates"
  )  +
  theme(axis.text.x = element_text(angle = 90))
cities_plot
```
Problem 2 - Birthweight
```{r, warning = FALSE, echo = FALSE}
library(modelr) 
library(mgcv)
set.seed(12345)
birthweight = read.csv(file = "./birthweight.csv")
birthweight_data = 
  birthweight %>%
  mutate(babysex = as.factor(babysex), frace = as.factor(frace), malform = as.factor(malform), 
         mrace = as.factor(mrace))
mod_maternalfactors = 
  birthweight_data %>%
  select(bwt, ppbmi, ppwt)
lm_maternalfactors = lm(bwt ~ ppbmi + ppwt, mod_maternalfactors)
lm_maternalfactors %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3) 
modelr::add_residuals(mod_maternalfactors, lm_maternalfactors) 
modelr::add_predictions(mod_maternalfactors, lm_maternalfactors)
mod_maternalfactors %>% 
  modelr::add_residuals(lm_maternalfactors) %>% 
  ggplot(aes(x = ppbmi + ppwt, y = resid)) + geom_violin()
birthweight_data %>%
  modelr::add_predictions(lm_maternalfactors) %>%
  modelr::add_residuals(lm_maternalfactors) %>%
  ggplot(aes(x = pred, y = resid)) + geom_point()
mod_birthleng_gestweek = 
  birthweight_data %>%
  select(bwt, blength, gaweeks)
lm_birthleng_gestweek = lm(bwt ~ blength + gaweeks, mod_birthleng_gestweek)
lm_birthleng_gestweek %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
modelr::add_residuals(mod_birthleng_gestweek, lm_birthleng_gestweek)
modelr::add_predictions(mod_birthleng_gestweek, lm_birthleng_gestweek)
mod_headlengthsex = 
  birthweight_data %>%
  select(bwt, bhead, blength, babysex)
lm_headlengthsex = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, mod_headlengthsex)
lm_headlengthsex %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
modelr::add_residuals(mod_headlengthsex, lm_headlengthsex)
modelr::add_predictions(mod_headlengthsex, lm_headlengthsex)
crossvalidate_birthdata = 
  crossv_mc(birthweight_data, 500) 
crossvalidate_birthdata = 
  crossvalidate_birthdata %>% 
  mutate(mod_maternalfactors = map(train, ~lm(bwt ~ ppbmi + ppwt, data = .x)),
         mod_birthleng_gestweek = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         mod_headlengthsex = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_maternalfactors = map2_dbl(mod_maternalfactors, test, ~rmse(model = .x, data = .y)),
         rmse_birthleng_gestweek = map2_dbl(mod_birthleng_gestweek, test, ~rmse(model = .x, data = .y)),
         rmse_headlengthsex = map2_dbl(mod_headlengthsex, test, ~rmse(model = .x, data = .y)))
crossvalidate_birthdata %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

